#diccionario contagios y recuperados
("contagios","recuperdos") range= 0,10:
 "contagios"=({"oruro":[2]},{"la paz":[5]}{"cochabamba":[6]}{"potosi":[7]}{"sucre":[4]}{"beni":[2]}{"pando":[5]}{"santa cruz":[2]}):
 "recuperados"=({"oruro":[9]},{"la paz":[5]}{"cochabamba":[1]}{"potosi":[3]}{"sucre":[6]}{"beni":[3]}{"pando":[4]}{"santa cruz":[1]}):
 for i in (= item):
 print ("recuperados","contagios")
#lista descuento en cine
precios={" "estudiante"=20%, "regular" =0% "adulto mayor" =30%:"}

 #ingresar lista 5 paises
 paises=[]
 for i in range (1,6):
   pais= input("ingrese nombre de pais:")
   paises.append(pais) 
 print=(paises)
