print(15+75)
print(190-75)
print (7*6)
print (91/8)
print (5==10)
print (2==2)
print (4<9)
print (9>5)
print (5+8)
print(max("Python"))
print(min("Python"))
print(len("Python"))
materia='Programacion Avanzada'
X=5.5
Y=8
print(materia)
nombre= input ('Ingrese su nombre completo')
print(nombre)
edad= input ('ingrese su edad')
print(edad)